/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({
    enabled: true
});


Ext.application({
    id: 'MyForm',
    views: [
        'Window'
    ],
    name: 'MyForm',

    log: function(txt) {
        var c = Ext.getCmp("console");

        var content = c.getValue();

        // TODO: make sure it's not getting too long

        // append text
        c.setValue(content + "\n" + txt);

        //c.addChildEls(txt);

        // scroll down
        c.scrollBy(0, 1, false);
    },

    launch: function() {
        Ext.create('MyForm.view.Window', {renderTo: Ext.getBody()});
        this.log("test ...");
        this.log("test ...");
        this.log("test ...");
        this.log("test ...");
        this.log("test ...");
        this.log("test ...");
        this.log("test ...");
        this.log("test ...");
        this.log("test ...");
        this.log("test ...");
        this.log("test ...");
        this.log("test ...");
        this.log("test ...");
        this.log("test ...");
        this.log("test ...");
        this.log("test ...");
        this.log("test ...");
        this.log("test ...");
        this.log("test ...");
        this.log("test ...");

    }

});
