/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({
    enabled: true
});


Ext.application({
    id: 'MyForm',
    models: [
        'MyModel'
    ],
    views: [
        'Window'
    ],
    name: 'MyForm',

    log: function(txt) {
        var c = Ext.getCmp("console");
        c.setAutoScroll(true);

        var content = c.getValue();

        // limit console length to N char
        var length = 1000;
        if (content.length > length) {
            content = content.substr(0, length);
        }


        // append text
        c.setValue(txt + "\n" + content);

        //c.addChildEls(txt);

        // scroll down
        c.scrollBy(0, 20000, false);
    },

    launch: function() {
        Ext.create('MyForm.view.Window', {renderTo: Ext.getBody()});
        this.log("launch() ...");


    }

});
