/*
 * File: app/view/Window.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyForm.view.Window', {
    extend: 'Ext.window.Window',

    autoRender: true,
    autoShow: true,
    height: 587,
    width: 458,
    layout: {
        align: 'stretch',
        type: 'vbox'
    },
    title: 'My Window',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    flex: 1,
                    layout: {
                        align: 'stretch',
                        type: 'vbox'
                    },
                    bodyPadding: 10,
                    items: [
                        {
                            xtype: 'fieldcontainer',
                            flex: 1,
                            height: 120,
                            width: 400,
                            items: [
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'Label'
                                },
                                {
                                    xtype: 'timefield',
                                    fieldLabel: 'Label'
                                },
                                {
                                    xtype: 'numberfield',
                                    fieldLabel: 'Label'
                                },
                                {
                                    xtype: 'htmleditor',
                                    height: 150,
                                    fieldLabel: 'Label'
                                },
                                {
                                    xtype: 'datefield',
                                    fieldLabel: 'Label'
                                },
                                {
                                    xtype: 'radiogroup',
                                    width: 400,
                                    fieldLabel: 'Label',
                                    items: [
                                        {
                                            xtype: 'radiofield',
                                            boxLabel: 'Box Label'
                                        },
                                        {
                                            xtype: 'radiofield',
                                            boxLabel: 'Box Label'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            layout: {
                                align: 'stretch',
                                pack: 'end',
                                type: 'hbox'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    text: 'MyButton'
                                },
                                {
                                    xtype: 'button',
                                    text: 'MyButton'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});