/*
 * File: app/view/Window.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyForm.view.Window', {
    extend: 'Ext.window.Window',

    autoRender: true,
    autoShow: true,
    height: 587,
    width: 458,
    layout: {
        type: 'border'
    },
    title: 'My Window',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'textfield',
                    region: 'south',
                    split: true,
                    height: 150,
                    id: 'console',
                    fieldStyle: 'font-family: courier, fixed; white-space: pre ! important;',
                    emptyText: 'Console'
                },
                {
                    xtype: 'form',
                    flex: 1,
                    region: 'center',
                    layout: {
                        align: 'stretch',
                        type: 'vbox'
                    },
                    bodyPadding: 10,
                    items: [
                        {
                            xtype: 'fieldcontainer',
                            flex: 1,
                            height: 120,
                            width: 400,
                            items: [
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'Name'
                                },
                                {
                                    xtype: 'combobox',
                                    fieldLabel: 'Language'
                                },
                                {
                                    xtype: 'numberfield',
                                    fieldLabel: 'Age'
                                },
                                {
                                    xtype: 'htmleditor',
                                    height: 150,
                                    fieldLabel: 'Bio',
                                    enableAlignments: false,
                                    enableFont: false,
                                    enableFontSize: false,
                                    enableSourceEdit: false
                                },
                                {
                                    xtype: 'datefield',
                                    fieldLabel: 'Birthdate'
                                },
                                {
                                    xtype: 'radiogroup',
                                    width: 400,
                                    fieldLabel: 'Sex',
                                    items: [
                                        {
                                            xtype: 'radiofield',
                                            boxLabel: 'Female'
                                        },
                                        {
                                            xtype: 'radiofield',
                                            boxLabel: 'Male'
                                        },
                                        {
                                            xtype: 'radiofield',
                                            boxLabel: 'Other'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            layout: {
                                align: 'stretch',
                                pack: 'end',
                                type: 'hbox'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    width: 80,
                                    text: 'Cancel'
                                },
                                {
                                    xtype: 'button',
                                    margins: '0 0 0 5',
                                    width: 80,
                                    text: 'Ok',
                                    listeners: {
                                        click: {
                                            fn: me.onButtonClick,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onButtonClick: function(button, e, eOpts) {
        MyForm.app.log("line 2 ....");
    }

});